/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HR;

import Business.EcoSystem;
import Business.Organization.CompanyOrg;
import Business.Organization.OldAgeHomeOrg;
import Business.Organization.OrganizationDirectory;
import Business.Organization.VeteransOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.HR.PrivilegedWorkArea;
import userinterface.HR.UnderPrivilegedWorkAreaPanel;

/**
 *
 * @author Tushar
 */
public class HRWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form HRWorkAreaPanel
     */
   JPanel userProcessContainer; UserAccount account; EcoSystem business; CompanyOrg companyOrg; OrganizationDirectory organizationDirectory;
   //OldAgeHomeOrg organization; 
   
//    public HRWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, CompanyOrg companyOrg, OrganizationDirectory organizationDirectory) {
//    initComponents();
//    this.userProcessContainer=userProcessContainer;
//    this.account=account;
//    this.business=business;
//    this.companyOrg=companyOrg;
//    this.organizationDirectory=organizationDirectory;
//    //this.organization=organization;
//    }

    

    public HRWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, CompanyOrg companyOrg, OrganizationDirectory organizationDirectory) {
    initComponents();
    this.userProcessContainer=userProcessContainer;
    this.account=account;
    this.business=business;
    this.companyOrg=companyOrg;
    this.organizationDirectory=organizationDirectory;  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        privilagedWorkArea = new javax.swing.JButton();
        underprivilagedWorkArea = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 0, 0));

        privilagedWorkArea.setText("Recruitment process for Previleged");
        privilagedWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privilagedWorkAreaActionPerformed(evt);
            }
        });

        underprivilagedWorkArea.setText("Recruitment process for Under Previleged");
        underprivilagedWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underprivilagedWorkAreaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Human Resource Manager  Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(privilagedWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(underprivilagedWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addComponent(privilagedWorkArea)
                .addGap(74, 74, 74)
                .addComponent(underprivilagedWorkArea)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void privilagedWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privilagedWorkAreaActionPerformed
        // TODO add your handling code here:
        PrivilegedWorkArea pwa= new PrivilegedWorkArea(userProcessContainer, business,companyOrg,account);
        userProcessContainer.add("PrivilegedWorkArea", pwa);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_privilagedWorkAreaActionPerformed

    private void underprivilagedWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underprivilagedWorkAreaActionPerformed
        // TODO add your handling code here:
        UnderPrivilegedWorkAreaPanel upp= new UnderPrivilegedWorkAreaPanel(userProcessContainer, business,companyOrg,organizationDirectory,account);
        userProcessContainer.add("UnderPrivilegedWorkAreaPanel", upp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_underprivilagedWorkAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton privilagedWorkArea;
    private javax.swing.JButton underprivilagedWorkArea;
    // End of variables declaration//GEN-END:variables
}
