/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOManager;

import Business.ApplicationWorkQueue.ApplicantWorkRequest;
import Business.ApplicationWorkQueue.WorkRequest;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Jobs.Job;
import Business.NGOPersonDirectory.NGOPerson;
import Business.Network.Network;
import Business.Organization.NGOOrg;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.VeteransOrg;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class NGOWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOWorkAreaPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem business;
    NGOOrg organization;
    OrganizationDirectory organizationDirectory;

    public NGOWorkAreaPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, NGOOrg organization, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.organization = organization;
        this.account = account;
        this.organizationDirectory = organizationDirectory;
        //populateJobTable();
        populateJobTable();
        populatePersonTable();
        populateWorkQueueTable();
    }

//    
    public void populateJobTable() {
        DefaultTableModel model = (DefaultTableModel) tblJob.getModel();

        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Job job : org.getJobDirectory().getJoblist()) {
                        if (job.getCategory().equals("Underprivileged")) {
                            Object[] row = new Object[2];
                            row[0] = job;
                            row[1] = job.getJobID();
                            model.addRow(row);
                        }
                    }
                }

            }
        }
    }

    public void populatePersonTable() {
        DefaultTableModel model = (DefaultTableModel) personTable.getModel();

        model.setRowCount(0);
        for (NGOPerson nGOPerson : organization.getnGOPersonDirectory().getNgoPersonList()) {
            {
                Object[] row = new Object[4];
                row[0] = nGOPerson;
                row[1] = nGOPerson.getFlag();
                model.addRow(row);
            }
        }

    }

    public void populateWorkQueueTable() {
        DefaultTableModel model = (DefaultTableModel) tblNGO.getModel();

        model.setRowCount(0);

        for (WorkRequest work : organization.getWorkQueue().getWorkRequestList()) {
            if (work instanceof ApplicantWorkRequest) {
                if (((ApplicantWorkRequest) work).getnGOPerson() != null) {
                    Object[] row = new Object[5];
                    row[0] = work;                    
                    row[1] = ((ApplicantWorkRequest) work).getApplicationID();
                    row[2] = ((ApplicantWorkRequest) work).getJob().getJobPosition();
                    row[3] = ((ApplicantWorkRequest) work).getSendername();
                    model.addRow(row);
                }
            }
        }
    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJob = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hrList = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        addPersonButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblNGO = new javax.swing.JTable();
        btnremove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NGO Person", "Eligibility"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(personTable);

        tblJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Job Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblJob);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job Positions ");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NGO Person List");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NGO Manager Work Area");

        hrList.setText("Send to HR");
        hrList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrListActionPerformed(evt);
            }
        });

        addPersonButton.setText("Add Person");
        addPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Person Name :");

        tblNGO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Application Status", "Application ID", "Job Position", "Applicant Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblNGO);

        btnremove.setText("Remove Person");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Applicantation Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnremove))
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPersonButton))))
                        .addContainerGap(88, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(hrList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hrList)
                    .addComponent(btnremove))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPersonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonButtonActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();
        if(!name.equals(""))
        {
        organization.getnGOPersonDirectory().addPerson(name, false,"unemployed");
        populatePersonTable();
        JOptionPane.showMessageDialog(addPersonButton, "NGO person added as applicant!");
        nameTextField.setText("");
        //populateJobTable();
        
        }
        else
            JOptionPane.showMessageDialog(addPersonButton, "Please enter a valid name");
    }//GEN-LAST:event_addPersonButtonActionPerformed

    private void hrListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrListActionPerformed
        int seletedVet = personTable.getSelectedRow();        
        int seletedJob = tblJob.getSelectedRow();
        if(seletedJob>=0 && seletedVet>=0)
        {
        NGOPerson nGOPerson = (NGOPerson) personTable.getValueAt(seletedVet, 0);
        nGOPerson.setFlag(true);
        nGOPerson.setJob((Job) tblJob.getValueAt(seletedJob, 0));
        nGOPerson.setHired("unhired");
        ApplicantWorkRequest applicantWorkRequest = new ApplicantWorkRequest();
        applicantWorkRequest.setnGOPerson((NGOPerson) personTable.getValueAt(seletedVet, 0));        
        applicantWorkRequest.setJob((Job) tblJob.getValueAt(seletedJob, 0));
        applicantWorkRequest.setFlag(true);
        applicantWorkRequest.setStatus("applied");
        applicantWorkRequest.setApplicationID(nGOPerson.getPersonID());
        applicantWorkRequest.setSendername(((NGOPerson) personTable.getValueAt(seletedVet, 0)).getName());        
        populatePersonTable();
        organization.getWorkQueue().getWorkRequestList().add(applicantWorkRequest);        
        business.getWorkQueue().getWorkRequestList().add(applicantWorkRequest);
        populateWorkQueueTable();
        JOptionPane.showMessageDialog(hrList, "Applicant profile successfully sent to company HR");
        }
        else
            JOptionPane.showMessageDialog(hrList, "Please choose valid profiles from Job Position And Ngo Person List tables");
    }//GEN-LAST:event_hrListActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        
        int selectedperson = personTable.getSelectedRow();
        if(selectedperson>=0)
        {
        NGOPerson nGOPerson = (NGOPerson) personTable.getValueAt(selectedperson, 0);
        
        organization.getnGOPersonDirectory().removeperson(nGOPerson);
        
        populatePersonTable();
        JOptionPane.showMessageDialog(btnremove, "Removed Applicant Succesfully");
    }
        else
               JOptionPane.showMessageDialog(btnremove, "Select Applicant to delete");
    }//GEN-LAST:event_btnremoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonButton;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton hrList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable personTable;
    private javax.swing.JTable tblJob;
    private javax.swing.JTable tblNGO;
    // End of variables declaration//GEN-END:variables
}
