/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Main;

//import Business.Applicant.ApplicantPersonalDetails;
import Business.Applicant.Applicant;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CompanyOrg;
import Business.Organization.Organization;
import Business.Role.ApplicantRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raj
 */
public class ReviewPage extends javax.swing.JPanel {

    /**
     * Creates new form SignupForm
     */
    
    JPanel container; EcoSystem business;

    

    ReviewPage(JPanel container, EcoSystem business) {
       initComponents();
        this.business=business;
        this.container=container;
        
       submitButton.setEnabled(Boolean.FALSE);
       
        
        
        
        
        
//        fnameTF.setText(applicant.getFirstName());
//        MnameTF.setText(applicant.getMiddleName());
//        LnameTF.setText(applicant.getLastName());
//        eaTF.setText(applicant.getEmailAddress());
//        cno1TF.setText(applicant.getPrimaryNumber());
//        cno2.setText(applicant.getSecondaryNumber());
//        ageTF.setText(applicant.getAge());
//        sexTF.setText(applicant.getSex());
//        careerTF.setText(applicant.getQualification());
//        educationTF.setText(applicant.getEducation());
//        a1TF.setText(applicant.getAddressLine1());
//        a2TF.setText(applicant.getAddressLine2());
//        lmTF.setText(applicant.getLandmark());
//        cTF.setText(applicant.getCity());
//        stateTF.setText(applicant.getState());
//        ctyTF.setText(applicant.getCountry());
//        zcTF.setText(applicant.getZipcode());
    }

    

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cno2TF = new javax.swing.JLabel();
        fnameTF = new javax.swing.JTextField();
        cno1TF = new javax.swing.JTextField();
        LnameTF = new javax.swing.JTextField();
        MnameTF = new javax.swing.JTextField();
        cno2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cno2TF1 = new javax.swing.JLabel();
        cno2TF2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        careerLevelComboBox = new javax.swing.JComboBox<>();
        educationLevelComboBox = new javax.swing.JComboBox<>();
        resumeTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        viewResume = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        confirmPasswordTF = new javax.swing.JPasswordField();
        enterPasswordTF = new javax.swing.JPasswordField();
        userNameTF = new javax.swing.JTextField();
        eaTF1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        submitDetails = new javax.swing.JButton();
        ageComboBox = new javax.swing.JComboBox<>();
        sexComboBox = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Application Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Career Level: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, 20));

        submitButton.setText("Submit Application");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 210, -1));

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Education Level:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Middle Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Primary Number:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        cno2TF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cno2TF.setForeground(new java.awt.Color(255, 255, 255));
        cno2TF.setText("Sex:");
        jPanel1.add(cno2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 20));

        fnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTFActionPerformed(evt);
            }
        });
        jPanel1.add(fnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, 30));

        cno1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cno1TFActionPerformed(evt);
            }
        });
        jPanel1.add(cno1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 190, 30));

        LnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTFActionPerformed(evt);
            }
        });
        jPanel1.add(LnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 190, 30));

        MnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameTFActionPerformed(evt);
            }
        });
        jPanel1.add(MnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, 30));

        cno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cno2ActionPerformed(evt);
            }
        });
        jPanel1.add(cno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Personal Information");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        cno2TF1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cno2TF1.setForeground(new java.awt.Color(255, 255, 255));
        cno2TF1.setText("Secondary Number:");
        jPanel1.add(cno2TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 20));

        cno2TF2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cno2TF2.setForeground(new java.awt.Color(255, 255, 255));
        cno2TF2.setText("Age:");
        jPanel1.add(cno2TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Qualification Information");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        careerLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Student", "Entry Level", "Experienced(Non-Manager)", "Manager", "Executive", "Senior Executive" }));
        careerLevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                careerLevelComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(careerLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 260, 20));

        educationLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Some high school coursework", "High School", "Bachelor's Degree", "Master's Degree", "Doctorate", "Professional" }));
        jPanel1.add(educationLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 260, 20));
        jPanel1.add(resumeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 260, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Upload Your Resume:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, 20));

        uploadButton.setText("Upload Resume");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        viewResume.setText("View Resume");
        viewResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResumeActionPerformed(evt);
            }
        });
        jPanel1.add(viewResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Enter Username:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Confirm Password:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Enter Password:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, 20));
        jPanel1.add(confirmPasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 200, 30));
        jPanel1.add(enterPasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 200, 30));
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 200, 30));

        eaTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(eaTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 200, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Enter Your Email Address:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        submitDetails.setText("Submit Details");
        submitDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(submitDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, -1, -1));

        ageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90+" }));
        jPanel1.add(ageComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, 30));

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female", "Other" }));
        jPanel1.add(sexComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 190, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void fnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTFActionPerformed

    private void cno1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cno1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cno1TFActionPerformed

    private void LnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTFActionPerformed

    private void MnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameTFActionPerformed

    private void cno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cno2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        JOptionPane.showMessageDialog(submitButton,"Application Submitted Succesfully");
        fnameTF.setEnabled(Boolean.FALSE);
        MnameTF.setEnabled(Boolean.FALSE);
        LnameTF.setEnabled(Boolean.FALSE);
        eaTF1.setEnabled(Boolean.FALSE);
        cno1TF.setEnabled(Boolean.FALSE);
        cno2.setEnabled(Boolean.FALSE);
        
        userNameTF.setEnabled(Boolean.FALSE);
        enterPasswordTF.setEnabled(Boolean.FALSE);
        confirmPasswordTF.setEnabled(Boolean.FALSE);
        eaTF1.setEnabled(Boolean.FALSE);
        ageComboBox.setEnabled(Boolean.FALSE);
        sexComboBox.setEnabled(Boolean.FALSE);
        educationLevelComboBox.setEnabled(Boolean.FALSE);
        careerLevelComboBox.setEnabled(Boolean.FALSE);
        resumeTextField.setEnabled(Boolean.FALSE);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser select = new JFileChooser();
        select.showOpenDialog(null);
        File f= select.getSelectedFile();
        String filename= f.getAbsolutePath();
        resumeTextField.setText(filename);

    }//GEN-LAST:event_uploadButtonActionPerformed

    private void eaTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaTF1ActionPerformed

    private void submitDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDetailsActionPerformed
        String fname = fnameTF.getText();
        String mname = MnameTF.getText();
        String lname = LnameTF.getText();
        //String email = eaTF.getText();
        String age = ageComboBox.getSelectedItem().toString();
        String sex = sexComboBox.getSelectedItem().toString();
        String primNo = cno1TF.getText();
        String secNo = cno2.getText();
        String education = educationLevelComboBox.getSelectedItem().toString();
        String qualification = careerLevelComboBox.getSelectedItem().toString();
        String resumeText = resumeTextField.getText();
        String username = userNameTF.getText();
        String pass = enterPasswordTF.getText();
        String confirm = confirmPasswordTF.getText();
        String email = eaTF1.getText();
        if(!fname.equals("") && !mname.equals("") &&!lname.equals("")&&!primNo.equals("")&&!secNo.equals("")&&!resumeText.equals("")&&!username.equals("")&&!pass.equals("")&&!confirm.equals("") && !email.equals("")&& !age.equals("") && !sex.equals("") && !education.equals("") && !qualification.equals("") )
        {
        Applicant applicant = business.getApplicantDirectory().addPersonalDetails(fname, mname, lname, age, sex, primNo, secNo, pass, username, email, education, qualification, resumeText);
        if(!pass.equals(confirm))
        {
            JOptionPane.showMessageDialog(submitDetails,"Passwords do no match,Re-enter passwords");
            
        }
        
        else if(pass.equals(confirm))
        {
        Applicant applicant1= business.getApplicantDirectory().createApplicantLogin(username, pass,email);
        for (Network network : business.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if(org instanceof CompanyOrg){
                            UserAccount ual = org.getUserAccountDirectory().creatApplicantUserAccount(username, pass, applicant1, new ApplicantRole(),email);
                        }
                    }

                }
            }
        submitButton.setEnabled(Boolean.TRUE);
        JOptionPane.showMessageDialog(submitDetails, "Details added succesfully");
        }
        }
        else
            JOptionPane.showMessageDialog(submitDetails, "Please enter valid details");
            
        //
    }//GEN-LAST:event_submitDetailsActionPerformed

    private void viewResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResumeActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + resumeTextField.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(viewResume, "Please choose a pdf compatible file type");
        }
    }//GEN-LAST:event_viewResumeActionPerformed

    private void careerLevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_careerLevelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_careerLevelComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LnameTF;
    private javax.swing.JTextField MnameTF;
    private javax.swing.JComboBox<String> ageComboBox;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> careerLevelComboBox;
    private javax.swing.JTextField cno1TF;
    private javax.swing.JTextField cno2;
    private javax.swing.JLabel cno2TF;
    private javax.swing.JLabel cno2TF1;
    private javax.swing.JLabel cno2TF2;
    private javax.swing.JPasswordField confirmPasswordTF;
    private javax.swing.JTextField eaTF1;
    private javax.swing.JComboBox<String> educationLevelComboBox;
    private javax.swing.JPasswordField enterPasswordTF;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resumeTextField;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitDetails;
    private javax.swing.JButton uploadButton;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JButton viewResume;
    // End of variables declaration//GEN-END:variables
}
