/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Applicant;

import Business.Applicant.Applicant;
import Business.Application.Application;
import Business.ApplicationWorkQueue.ApplicantWorkRequest;
import Business.ApplicationWorkQueue.WorkRequest;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Jobs.Job;
import Business.Network.Network;
import Business.Organization.CompanyOrg;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tushar
 */
public class ApplicantRoleWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicantRoleWorkArea
     */
    JPanel userProcessContainer;
    EcoSystem business;
    CompanyOrg organization;
    UserAccount userAccount;

    public ApplicantRoleWorkAreaPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount, CompanyOrg organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organization = organization;
        //populateWorkQueueTable();
        populateJobTable();
        populateWorkQueueTable();
    }

    public void populateJobTable() {
        DefaultTableModel model = (DefaultTableModel) tblJob.getModel();

        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (Job job : org.getJobDirectory().getJoblist()) {
                        if (job.getCategory().equals("Priviledged")) {
                            Object[] row = new Object[3];
                            row[0] = job;
                            row[1] = job.getJobID();
                            //row[2] = job.getCategory();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }

    public void populateWorkQueueTable() {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);
        for (UserAccount useraccount : organization.getUserAccountDirectory().getUserAccountList()) {
            for (WorkRequest work : useraccount.getWorkQueue().getWorkRequestList()) {
                if (useraccount.getApplicant() != null) {
                    if (useraccount.getApplicant().getUserName().equals(userAccount.getApplicant().getUserName())) {
                        if (work instanceof ApplicantWorkRequest) {
                            Object[] row = new Object[4];
                            row[0] = work.getStatus();
                            row[1] = ((ApplicantWorkRequest) work).getApplicationID();
                            row[2] = ((ApplicantWorkRequest) work).getJob().getJobPosition();
                            row[3] = ((ApplicantWorkRequest) work).getSender();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJob = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnApplyjob = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        tblJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Position", "Job ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJob);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Applicant Work Area");

        btnApplyjob.setText("Apply for the selected job");
        btnApplyjob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyjobActionPerformed(evt);
            }
        });

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Application Status", "Application ID", "Job Position", "Applicant Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Applications");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jobs Available");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(29, 29, 29)
                .addComponent(btnApplyjob)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyjob))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyjobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyjobActionPerformed
        int selectedRow = tblJob.getSelectedRow();

        if (selectedRow >= 0) {
            Application application = new Application();
            Job job = (Job) tblJob.getValueAt(selectedRow, 0);
            application.setJob(job);
            application.setApplicant(userAccount.getApplicant());
            
            //Job job = (Job) tblJob.getValueAt(selectedRow, 0);
            ApplicantWorkRequest request = new ApplicantWorkRequest();
            request.setApplicationID(application.getApplicationID());
            request.setJob(job);
            request.setStatus("Applied");
            request.setSender(userAccount);
            request.setSendername(userAccount.getApplicant().getFirstName());
            request.setEmail(userAccount.getEmail());
            organization.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            business.getWorkQueue().getWorkRequestList().add(request);
            populateWorkQueueTable();
    }//GEN-LAST:event_btnApplyjobActionPerformed
    else
            JOptionPane.showMessageDialog(btnApplyjob, "Please select a job from Jobs Available table to apply");
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyjob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    private javax.swing.JTable tblJob;
    // End of variables declaration//GEN-END:variables

}